### ISSUE TITLE
cannot use additional data structures

### ISSUE THREAD

**Issue by benjiwright** [careercup/CtCI-6th-Edition-CSharp#1]
**Class**: Q1_01_Is_Unique.cs
**Method**: IsUniqueChars2( )

The question states:

> you cannot use additional data structures

but in the second solution creates an array of boolean

` var charSet = new bool[256];`

**Comment by trycatchdonothing** [comment]
I think it's showing both ways...with an additional data structure and without. There are actually two questions for 1.1 in the book, so this makes sense.

**Comment by AmrutaMoghe** [comment]
Chap1 , Question 1.2 - Check Permutations

Can be done in another way as follows

public bool CheckPermutation(string word1, string word2)
        {
            var result1 = word1 + word1;
            return result1.IndexOf(word2) > -1;
        }
